title: "[Titolo]"
labels: ["votazione"]
body:
  - type: textarea
    id: descrizione
    attributes:
      label: Descrizione della proposta
      placeholder: Copia la descrizione dalla proposta originale
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        /poll "Qual è la tua preferenza?" "Favorevole" "Contrario" "Astenuto"

