title: "Titolo della votazione"
labels: ["votazione"]
body:
  - type: input
    id: proposta_url
    attributes:
      label: Link alla discussione originale
      placeholder: Inserisci qui l'URL della proposta da votare
    validations:
      required: true

  - type: textarea
    id: descrizione
    attributes:
      label: Breve descrizione della votazione
      placeholder: Inserisci qui il testo della votazione
    validations:
      required: true


