title: "[VOTAZIONE] Titolo della votazione"
labels: ["votazione"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Questa votazione si riferisce alla proposta originale. Leggi prima la proposta:

        [Apri proposta originale]({{PROPOSTA_URL}})

  - type: textarea
    id: descrizione
    attributes:
      label: Breve descrizione della votazione
      placeholder: Inserisci qui il testo della votazione
    validations:
      required: true

  

